/* Generated By:JJTree: Do not edit this line. ASTLink.java */
package uk.ac.ed.wimo.stix.view.wiki;

public class ASTLink extends SimpleNode {
  public ASTLink(int id) {
    super(id);
  }

  public ASTLink(wiki p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(wikiVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
    String text;
    public void setText(String t) { text = t; }
    public String getText() { return text; }

    String link;
    public void setLinkText(String t) { link = t; }
    public String getLinkText() { return link; }

    public String toString() 
    {
	String rtn = "<a [";
	rtn += text;
	if (link != null) rtn += "|" + link;
	rtn += "] >";
	return rtn;
    }
 

}
