/* Generated By:JJTree: Do not edit this line. ASTText.java */
package uk.ac.ed.wimo.stix.view.wiki;


public class ASTText extends SimpleNode {
  public ASTText(int id) {
    super(id);
  }

  public ASTText(wiki p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(wikiVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }

}
