/* Generated By:JJTree: Do not edit this line. ASTLine.java */
package uk.ac.ed.wimo.stix.view.wiki;

public class ASTLine extends SimpleNode {
  public ASTLine(int id) {
    super(id);
  }

  public ASTLine(wiki p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(wikiVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
