/* Generated By:JavaCC: Do not edit this line. ConditionConstants.java */
package uk.ac.ed.inf.wimo.stix.agent.util.condition;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ConditionConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int HASH = 5;
  /** RegularExpression Id. */
  int ADD = 6;
  /** RegularExpression Id. */
  int SUB = 7;
  /** RegularExpression Id. */
  int MUL = 8;
  /** RegularExpression Id. */
  int DIV = 9;
  /** RegularExpression Id. */
  int OPENPAR = 10;
  /** RegularExpression Id. */
  int CLOSEPAR = 11;
  /** RegularExpression Id. */
  int EQUAL = 12;
  /** RegularExpression Id. */
  int LESS = 13;
  /** RegularExpression Id. */
  int MOR = 14;
  /** RegularExpression Id. */
  int LESSEQUAL = 15;
  /** RegularExpression Id. */
  int MOREEQUAL = 16;
  /** RegularExpression Id. */
  int AND = 17;
  /** RegularExpression Id. */
  int OR = 18;
  /** RegularExpression Id. */
  int NUMBER = 19;
  /** RegularExpression Id. */
  int IDENTIFIER = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"#\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"(\"",
    "\")\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"AND\"",
    "\"OR\"",
    "<NUMBER>",
    "<IDENTIFIER>",
  };

}
